# Generated by Django 5.2.6 on 2025-12-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0002_usersignin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersignin",
            name="email",
        ),
        migrations.AddField(
            model_name="usersignin",
            name="success",
            field=models.BooleanField(default=False),
        ),
    ]
